elasticsearch:
  build: elasticsearch/
  ports:
    - "9200:9200"
logstash:
  #image: logstash:latest
  build: logstash/
  command: logstash --pluginpath /etc/logstash/conf.d/extras -f /etc/logstash/conf.d/logstash.conf #-v --debug --verbose
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "5000:5000"
  links:
    - elasticsearch
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
